version: '3.8'
services:
  server:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/server/data
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my_custom_network
    ports:
      - "4220:4220"
    environment:
      - TZ=America/Los_Angeles
networks:
  my_custom_network:
    driver: bridge