version: '3.8'
services:
  server:
    container_name: panthera_gptaidbot
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/server/data
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=
      - LANGCHAIN_PROJECT="panthera"
      - OPENAI_API_KEY=
      - SERPER_API_KEY=
      - WOLFRAM_ALPHA_APPID=