version: '3.8'
services:
  server:
    # Container name
    container_name: panthera
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/server/data
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=<your-api-key>
      - LANGCHAIN_PROJECT=<your-project>  # if not specified, defaults to "default"
      - OPENAI_API_KEY=<your-openai-api-key>
